version: "3.9"

services:
  nextjs:
    image: ghcr.io/12bsg12/eris.mentor:latest  # будет обновляться из GHCR
    container_name: nextjs
    env_file:
      - .env
    restart: always
    networks:
      eris-net:
        ipv4_address: 172.22.0.3

networks:
  eris-net:
    external: true