version: "3.9"

services:
  nextjs:
    image: ghcr.io/12bsg12/eris.mentor:latest  # будет обновляться из GHCR
    container_name: nextjs
    restart: always
    networks:
      - nginx_eris-net

networks:
  nginx_eris-net:
    external: true