import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import ClientAuthGuard from '@/components/ClientAuthGuard';

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ClientAuthGuard>{children}</ClientAuthGuard>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
