import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import ClientAuthGuard from '@/components/ClientAuthGuard';
import { CurrentUserStoreProvider } from '@/providers/current-user-provider';

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CurrentUserStoreProvider>
          <AppRouterCacheProvider>
            <ClientAuthGuard>{children}</ClientAuthGuard>
          </AppRouterCacheProvider>
        </CurrentUserStoreProvider>
      </body>
    </html>
  );
}
